### Surfing on dataset of constructors, drivers and quality of F1 cars
We want to undestand which values we have

In [3]:
import pandas as pd

In [25]:
constructors = pd.read_csv('../dataset/constructors.csv')
drivers = pd.read_csv('../dataset/drivers.csv')
qualifyings = pd.read_csv('../dataset/qualifying.csv')
circuits = pd.read_csv('../dataset/circuits.csv')
races = pd.read_csv('../dataset/races.csv')

constructors

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
...,...,...,...,...,...
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team
211,215,rb,RB F1 Team,Italian,http://en.wikipedia.org/wiki/RB_Formula_One_Team

In [11]:
drivers

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
856,858,sargeant,2,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,30,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
860,862,doohan,61,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan

In [12]:
qualifyings

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236
...,...,...,...,...,...,...,...,...,...
10489,10547,1144,848,3,23,16,1:23.821,\N,\N
10490,10548,1144,855,15,24,17,1:23.880,\N,\N
10491,10549,1144,1,131,44,18,1:23.887,\N,\N
10492,10550,1144,861,3,43,19,1:23.912,\N,\N
10493,10551,1144,862,214,61,20,1:24.105,\N,\N

In [21]:
circuits

,circuitId,circuitRef,name,location,country,lat,lng,alt,url,cluster_id
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,cluster_asia_pacific
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...,cluster_asia_pacific
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...,cluster_middle_east
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...,cluster_europe
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park,cluster_europe
...,...,...,...,...,...,...,...,...,...,...
72,76,mugello,Autodromo Internazionale del Mugello,Mugello,Italy,43.99750,11.37190,255,http://en.wikipedia.org/wiki/Mugello_Circuit,cluster_europe
73,77,jeddah,Jeddah Corniche Circuit,Jeddah,Saudi Arabia,21.63190,39.10440,15,http://en.wikipedia.org/wiki/Jeddah_Street_Cir...,cluster_middle_east
74,78,losail,Losail International Circuit,Al Daayen,Qatar,25.49000,51.45420,12,http://en.wikipedia.org/wiki/Losail_Internatio...,cluster_middle_east
75,79,miami,Miami International Autodrome,Miami,USA,25.95810,-80.23890,0,http://en.wikipedia.org/wiki/Miami_Internation...,cluster_americas
76,80,vegas,Las Vegas Strip Street Circuit,Las Vegas,USA,36.11470,-115.17300,642,https://en.wikipedia.org/wiki/Las_Vegas_Grand_...,cluster_americas

In [26]:
races

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1144,1164,2025,20,32,Mexico City Grand Prix,2025-11-02,20:00:00,https://en.wikipedia.org/wiki/2024_Mexico_City...,2024-10-25,18:30:00,2024-10-25,22:00:00,2024-10-26,17:30:00,2024-10-26,21:00:00,\N,\N
1145,1165,2025,21,18,São Paulo Grand Prix,2025-11-09,17:00:00,https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...,2024-11-01,14:30:00,2024-11-01,18:30:00,\N,\N,2024-11-02,18:00:00,2024-11-02,14:00:00
1146,1166,2025,22,80,Las Vegas Grand Prix,2025-11-23,06:00:00,https://en.wikipedia.org/wiki/2024_Las_Vegas_G...,2024-11-21,02:30:00,2024-11-21,06:00:00,2024-11-22,02:30:00,2024-11-22,06:00:00,\N,\N
1147,1167,2025,23,78,Qatar Grand Prix,2025-11-30,17:00:00,https://en.wikipedia.org/wiki/2024_Qatar_Grand...,2024-11-29,13:30:00,2024-11-29,17:30:00,\N,\N,2024-11-30,17:00:00,2024-11-30,13:00:00
1148,1168,2025,24,24,Abu Dhabi Grand Prix,2025-12-07,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,2024-12-06,13:00:00,2024-12-07,10:30:00,2024-12-07,14:00:00,\N,\N

In [34]:
df_merge_races_circuits_qualifyings = pd.merge(races, circuits, on='circuitId')
df_merge_races_circuits_qualifyings = pd.merge(df_merge_races_circuits_qualifyings, qualifyings, on='raceId')
df_merge_races_circuits_qualifyings

,raceId,year,round,circuitId,name_x,date,time,url_x,fp1_date,fp1_time,...,url_y,cluster_id,qualifyId,driverId,constructorId,number,position,q1,q2,q3
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,...,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,cluster_asia_pacific,2986,18,23,22,1,1:25.211,1:24.855,1:26.202
1,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,...,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,cluster_asia_pacific,2987,22,23,23,2,1:25.006,1:24.783,1:26.505
2,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,...,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,cluster_asia_pacific,2988,20,9,15,3,1:25.938,1:25.121,1:26.830
3,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,...,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,cluster_asia_pacific,2989,9,2,5,4,1:25.922,1:25.152,1:26.914
4,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,...,http://en.wikipedia.org/wiki/Melbourne_Grand_P...,cluster_asia_pacific,2990,3,3,16,5,1:25.846,1:25.123,1:26.973
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10489,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,...,http://en.wikipedia.org/wiki/Yas_Marina_Circuit,cluster_middle_east,10547,848,3,23,16,1:23.821,\N,\N
10490,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,...,http://en.wikipedia.org/wiki/Yas_Marina_Circuit,cluster_middle_east,10548,855,15,24,17,1:23.880,\N,\N
10491,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,...,http://en.wikipedia.org/wiki/Yas_Marina_Circuit,cluster_middle_east,10549,1,131,44,18,1:23.887,\N,\N
10492,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,...,http://en.wikipedia.org/wiki/Yas_Marina_Circuit,cluster_middle_east,10550,861,3,43,19,1:23.912,\N,\N
10493,1144,2024,24,24,Abu Dhabi Grand Prix,2024-12-08,13:00:00,https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...,2024-12-06,09:30:00,...,http://en.wikipedia.org/wiki/Yas_Marina_Circuit,cluster_middle_east,10551,862,214,61,20,1:24.105,\N,\N

In [27]:
df_merge = pd.merge(qualifyings, drivers, on='driverId')
df_merge

,qualifyId,raceId,driverId,constructorId,number_x,position,q1,q2,q3,driverRef,number_y,code,forename,surname,dob,nationality,url
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869,kubica,88,KUB,Robert,Kubica,1984-12-07,Polish,http://en.wikipedia.org/wiki/Robert_Kubica
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178,massa,19,MAS,Felipe,Massa,1981-04-25,Brazilian,http://en.wikipedia.org/wiki/Felipe_Massa
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10489,10547,1144,848,3,23,16,1:23.821,\N,\N,albon,23,ALB,Alexander,Albon,1996-03-23,Thai,http://en.wikipedia.org/wiki/Alexander_Albon
10490,10548,1144,855,15,24,17,1:23.880,\N,\N,zhou,24,ZHO,Guanyu,Zhou,1999-05-30,Chinese,http://en.wikipedia.org/wiki/Zhou_Guanyu
10491,10549,1144,1,131,44,18,1:23.887,\N,\N,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
10492,10550,1144,861,3,43,19,1:23.912,\N,\N,colapinto,43,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
10493,10551,1144,862,214,61,20,1:24.105,\N,\N,doohan,61,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan

In [ ]:
# Search the driver with the most pole positions
pole_positions = df_merge[df_merge['position'] == 1]
pole_counts = pole_positions['driverId'].value_counts()
pole_counts
top_driver_id = pole_counts.idxmax()
top_driver = drivers[drivers['driverId'] == top_driver_id]
top_driver

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton

In [45]:
# Search the driver with the most pole positions in every circuit
merge = pd.merge(df_merge, df_merge_races_circuits_qualifyings, on="raceId")
merge
merge_pole_positions = merge[merge['position_x'] == 1]
merge_pole_counts = merge_pole_positions.groupby('circuitId_x')['driverId_x'].value_counts()
merge_pole_counts
top_drivers_per_circuit = merge_pole_counts.groupby(level=0).idxmax()
top_drivers_per_circuit_info = []
for (circuitId, driverId) in top_drivers_per_circuit:
    circuit_name = circuits[circuits['circuitId'] == circuitId]['name'].values[0]
    driver_info = drivers[drivers['driverId'] == driverId][['forename', 'surname']].values[0]
    top_drivers_per_circuit_info.append((circuit_name, driver_info[0], driver_info[1]))
top_drivers_per_circuit_info

[('Albert Park Grand Prix Circuit', 'Lewis', 'Hamilton'),
 ('Sepang International Circuit', 'Lewis', 'Hamilton'),
 ('Bahrain International Circuit', 'Sebastian', 'Vettel'),
 ('Circuit de Barcelona-Catalunya', 'Lewis', 'Hamilton'),
 ('Istanbul Park', 'Felipe', 'Massa'),
 ('Circuit de Monaco', 'Charles', 'Leclerc'),
 ('Circuit Gilles Villeneuve', 'Lewis', 'Hamilton'),
 ('Circuit de Nevers Magny-Cours', 'Damon', 'Hill'),
 ('Silverstone Circuit', 'Lewis', 'Hamilton'),
 ('Hockenheimring', 'Gerhard', 'Berger'),
 ('Hungaroring', 'Lewis', 'Hamilton'),
 ('Valencia Street Circuit', 'Sebastian', 'Vettel'),
 ('Circuit de Spa-Francorchamps', 'Lewis', 'Hamilton'),
 ('Autodromo Nazionale di Monza', 'Lewis', 'Hamilton'),
 ('Marina Bay Street Circuit', 'Lewis', 'Hamilton'),
 ('Fuji Speedway', 'Lewis', 'Hamilton'),
 ('Shanghai International Circuit', 'Lewis', 'Hamilton'),
 ('Autódromo José Carlos Pace', 'Lewis', 'Hamilton'),
 ('Indianapolis Motor Speedway', 'Michael', 'Schumacher'),
 ('Nürburgring', 'Mark', 'Webber'),
 ('Autodromo Enzo e Dino Ferrari', 'Michael', 'Schumacher'),
 ('Suzuka Circuit', 'Sebastian', 'Vettel'),
 ('Yas Marina Circuit', 'Lewis', 'Hamilton'),
 ('Autódromo Juan y Oscar Gálvez', 'David', 'Coulthard'),
 ('Circuito de Jerez', 'Michael', 'Schumacher'),
 ('Autódromo do Estoril', 'Gerhard', 'Berger'),
 ('Okayama International Circuit', 'Ayrton', 'Senna'),
 ('Adelaide Street Circuit', 'Nigel', 'Mansell'),
 ('Autódromo Hermanos Rodríguez', 'Max', 'Verstappen'),
 ('Circuit Paul Ricard', 'Lewis', 'Hamilton'),
 ('Korean International Circuit', 'Sebastian', 'Vettel'),
 ('Circuit Park Zandvoort', 'Max', 'Verstappen'),
 ('Buddh International Circuit', 'Sebastian', 'Vettel'),
 ('Circuit of the Americas', 'Lewis', 'Hamilton'),
 ('Red Bull Ring', 'Max', 'Verstappen'),
 ('Sochi Autodrom', 'Lewis', 'Hamilton'),
 ('Baku City Circuit', 'Charles', 'Leclerc'),
 ('Autódromo Internacional do Algarve', 'Lewis', 'Hamilton'),
 ('Autodromo Internazionale del Mugello', 'Lewis', 'Hamilton'),
 ('Jeddah Corniche Circuit', 'Sergio', 'Pérez'),
 ('Losail International Circuit', 'Max', 'Verstappen'),
 ('Miami International Autodrome', 'Sergio', 'Pérez'),
 ('Las Vegas Strip Street Circuit', 'Charles', 'Leclerc')]